import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1787660724695 implements MigrationInterface {
    name = 'InitialSchema1787660724695'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Required for uuid_generate_v4(), used as the default on every uuid primary key below.
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);

        // Customers table: one row per customer, uuid primary key generated by Postgres.
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "image_url" character varying(255) NOT NULL, CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);

        // Invoices table. The UNIQUE constraint on (customer_id, date, amount) lets
        // seed/import scripts use ON CONFLICT DO NOTHING to stay idempotent, since
        // invoices otherwise have no natural key (id is server-generated).
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "amount" integer NOT NULL, "status" character varying(255) NOT NULL, "date" date NOT NULL, CONSTRAINT "UQ_f2c225ce79a94b19d1f8048c9ee" UNIQUE ("customer_id", "date", "amount"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);

        // Users table: email is unique since it's used as the login identifier.
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "email" text NOT NULL, "password" text NOT NULL, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);

        // Revenue table: one row per month, month is the natural primary key.
        await queryRunner.query(`CREATE TABLE "revenue" ("month" character varying(4) NOT NULL, "revenue" integer NOT NULL, CONSTRAINT "PK_c8871bb060df56e83532251e4e1" PRIMARY KEY ("month"))`);

        // Invoice -> Customer foreign key. ON DELETE RESTRICT: invoices are financial
        // records and must never be silently cascade-deleted or orphaned. No code path
        // deletes customers today; if one is added later it must handle a customer's
        // invoices explicitly instead of relying on the database to clean them up.
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_65e3145f317bd655481d3f96c74" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Drop the foreign key first since invoices depends on customers.
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_65e3145f317bd655481d3f96c74"`);
        // Drop tables in reverse-dependency order (invoices before customers).
        await queryRunner.query(`DROP TABLE "revenue"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TABLE "customers"`);
    }

}
